bracketSpacing: true
plugins:
  - "@trivago/prettier-plugin-sort-imports"
printWidth: 120
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "all"

overrides:
  - files: "*.tsx"
    options:
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderParserPlugins: ["jsx", "typescript"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
